drive/urls.py
from django.urls import path
from .views import( FolderListView, FileListView, get_presigned_url, 
                   get_presigned_url_for_download)

app_name='drive'

urlpatterns = [
    path('folders/<str:folder_id>/', FolderListView.as_view()),
    path('folders/', FolderListView.as_view()),
    path('folders/', FolderListView.as_view()),
    path('files/upload-url/', get_presigned_url), 
    path('files/<str:file_id>/download-url/', get_presigned_url_for_download),
    path('files/<str:file_id>/', FileListView.as_view()),
    path('files/', FileListView.as_view()),
    path('', FolderListView.as_view(), name='list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("drive/", include("drive.urls")),
    path("users/", include("users.urls")),
    path('', TemplateView.as_view(template_name='landing_page.html'))
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import(login_view, signup_view)

app_name = "users"

urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', signup_view, name='signup'),
    path('logout/', LogoutView.as_view(), name='logout')
]

drive/models.py
from django.db import models
from django.contrib.auth.models import User # pylint: disable=imported-auth-user

# Create your models here.

class Folder(models.Model):
    ''' Folder Model '''
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    parent_folder = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    is_empty = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

class File(models.Model):
    ''' File Model '''
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    object_key = models.CharField(max_length=300)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

drive/views.py
import json
import uuid
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import View
from django.views.decorators.http import require_GET
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from drive import json_loads_suppress_exc

from .models import Folder, File
from .integrations import generate_presigned_url, delete_object, \
    delete_multiple_objects, object_exists, IntegrationException

INVALID_REQUEST_BODY_ERROR = "Invalid Request Body"

class FolderListView(LoginRequiredMixin, View):
    ''' Handler for CRUD operations of Folder Model 
        Current Folder ID of the user stores the ID of the folder where user is in currently.
        Folders stored in the Root Folder has no folder ID. They are just fetched on the basis of User ID 
    '''
    template_name = "main.html"
    def get(self, request, *args, **kwargs):
        ''' Get all the files and folders inside the current folder. '''
        context = {}
        folder_id = self.kwargs.get('folder_id', None)
        if folder_id:    
            folder = Folder.objects.get(id=folder_id, user=request.user)
            context['parent_folder_id'] = folder.parent_folder and folder.parent_folder.id
        context['folder_id'] = folder_id
        context['folders'] = Folder.objects.filter(parent_folder=folder_id, user=request.user)
        context['files'] =  File.objects.filter(folder=folder_id, user=request.user)
        request.session['current_folder_id'] = folder_id 
        return render(request, 'main.html', context)
    
    def post(self, request, *args, **kwargs):
        ''' Create a new Folder Object '''
        body_data = json_loads_suppress_exc(request.body)
        if not body_data:
            return JsonResponse({"message": INVALID_REQUEST_BODY_ERROR}, status=400)
        folder_name = body_data.get('folder_name')
        current_folder_id = request.session.get('current_folder_id')
        if not folder_name:
            return JsonResponse({"message": 'Folder Name is mandatory'}, status=400)
        Folder.objects.create(
            name=folder_name, parent_folder_id=current_folder_id, user=request.user)
        return JsonResponse({"message": "Folder created succesfully "}, status=200)

    def put(self, request, *args, **kwargs):
        ''' Update Folder Name '''
        folder_id = self.kwargs.get('folder_id')
        body_data = json_loads_suppress_exc(request.body)
        if not body_data:
            return JsonResponse({"message": INVALID_REQUEST_BODY_ERROR}, status=400)
        update_folder_name = body_data.get('folder_name')
        if not update_folder_name:
            return JsonResponse(
                {"message": "Folder ID and New Folder Name is mandatory"}, status=400)
        folder = Folder.objects.get(id=folder_id, user=request.user)
        folder.name = update_folder_name
        folder.save()
        return JsonResponse({"message": "Updated Succesfully"}, status=200)
    
    def delete(self, request, *args, **kwargs):
        ''' To delete a folder '''
        folder_id = self.kwargs.get('folder_id')
        folder = Folder.objects.get(id=folder_id, user=request.user)
        try:
            self._delete_folder(folder, str(request.user.id))
        except IntegrationException as e:
            return JsonResponse({"message": "Failed to Delete Folder"}, status=500)
        return JsonResponse({"message": "File Deleted Successfully"}, status=200)


    def _delete_folder(self, folder, object_prefix):
        '''
            This Function ensures to recursively 
            delete all the files and folder inside 
            the target folder that needs to be deleted
        '''
        folders_inside_folder = Folder.objects.filter(parent_folder=folder)
        for inner_folder in list(folders_inside_folder):
            self._delete_folder(inner_folder, object_prefix)
        files_inside_folder = File.objects.filter(folder=folder)
        files_object_keys = list(map( lambda x: str(x.object_key),files_inside_folder))
        if files_object_keys:
            delete_multiple_objects(files_object_keys, object_prefix)
            files_inside_folder.delete()
        folder.delete()

class FileListView(LoginRequiredMixin, View):
    ''' Handler for CRUD operations of File Object 
        Files stored in the Root Folder has no folder ID. They are just fetched on the basis of User ID 
    '''

    def put(self, request, *args, **kwargs):
        ''' To rename a file '''
        file_id = self.kwargs.get('file_id')
        if not file_id:
            return JsonResponse({"message": "File ID not present"}, status=400)
        body_data = json_loads_suppress_exc(request.body)
        if not body_data:
            return JsonResponse({"message": INVALID_REQUEST_BODY_ERROR}, status=400)
        update_file_name = body_data.get('file_name')
        file = File.objects.get(id=file_id, user=request.user)
        file.name = update_file_name
        file.save()
        return JsonResponse({"message": "Updated Succesfully"}, status=200)
    
    def delete(self, request, *args, **kwargs):
        ''' To Delete a file object. First we delete from S3 bucket and then from the DB'''
        try:
            file_id = self.kwargs.get('file_id')
            if not file_id:
                return JsonResponse({"message": "File ID not present"}, status=400)
            current_folder_id = request.session.get('current_folder_id')
            if current_folder_id:
                current_folder = Folder.objects.get(id=current_folder_id, user=request.user)
                current_folder.is_empty = False
                current_folder.save()
            else:
                current_folder = None
            file = File.objects.get(id=file_id, user=request.user)
            # If S3 deletion fail it will raise error and the file.delete() call will not be invoked
            delete_object(file.object_key, str(request.user.id))
            file.delete() 
        except IntegrationException as e:
            return JsonResponse({"message": "Error while Deleteing File", "exc": str(e)}, status=500)
        return JsonResponse({"message": "File Deleted Successfully"}, status=200)

    def post(self, request, *args, **kwargs):
        ''' 
            To Create a file object. Since the file is uploaded to S3 through frontend. 
            When the upload is completed from frontend it initiates call to this function
            which then again verifies that the object has been uploaded to S3 and only 
            then it creates a file object in our database
        '''
        try:
            body_data = json.loads(request.body)
            object_key = body_data.get('object_key')
            file_name = body_data.get('file_name')
            folder_id = body_data.get('folder_id', "")
            if not file_name or not object_key:
                return JsonResponse({"message": "File Name and Object key is required"}, status=400)
            folder=None
            if folder_id:
                folder = Folder.objects.get(id=folder_id, user=request.user)
            if object_exists(object_key, str(request.user.id)):
                file = File.objects.create(
                    name=file_name,
                    object_key=object_key,
                    folder=folder,
                    user=request.user
                )
                return JsonResponse(
                    {"message": "File Created Successfully", "id": file.id}, status=200) 
            return JsonResponse(
                {"message": f"No Object with the given key exists - {object_key} "}, status=404)
        except IntegrationException as e:
            return JsonResponse(
                {"message": "Error while creating file"}, status=500) 

@require_GET
@login_required
def get_presigned_url(request, *args, **kwargs):
    ''' 
        This function returns the presigned url from S3 to the frontend to upload the object
    '''
    try:
        object_key = uuid.uuid4()
        presigned_url = generate_presigned_url(object_key=object_key, 
                                            prefix=str(request.user.id),for_upload=True)
    except IntegrationException:
        return JsonResponse({"message": "Error while getting download url"}, status=500)
    return JsonResponse({"presigned_url": presigned_url, "object_key": object_key}, status=200)

@require_GET
@login_required
def get_presigned_url_for_download(request, file_id, *args, **kwargs):
    '''
        This function returns presigned url for object download
    '''
    try:
        file = File.objects.get(id=file_id)
        presigned_url = generate_presigned_url(object_key=file.object_key, 
                                           prefix=str(request.user.id), 
                                           file_name=file.name, for_upload=False)
    except IntegrationException:
        return JsonResponse({"message": "Error while getting download url"}, status=500)
    return JsonResponse({"presigned_url": presigned_url}, status=200)

drive/templates/landing_page.html
{% load static %}
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Drive</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/Navbar-Right-Links-icons.css' %}">
</head>

<body style="border-color: var(--bs-btn-disabled-color);">
    <nav class="navbar navbar-expand-md bg-body py-3">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href=""><span class="fs-3 fw-bold">Drive</span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-2"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-2">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"></li>
                    <li class="nav-item"></li>
                    <li class="nav-item"><a class="nav-link fs-6 link-primary" href="{% url 'users:login' %}" style="font-size: 16px;">Sign In</a></li>
                </ul><a class="btn btn-primary ms-md-2" role="button" href="{% url 'drive:list' %}" style="border-radius: 5px;padding: 8px 24px;">Go To Drive</a>
            </div>
        </div>
    </nav>
    <section class="py-4 py-xl-5">
        <div class="container">
            <div class="text-center p-4 p-lg-5">
                <h1 class="fw-bold mb-4"><span style="font-weight: normal !important; color: rgb(13, 13, 13);">Store and Access Your Files From Anywhere</span></h1>
                <p class="mb-4" style="font-size: 16px;"><span style="color: rgb(13, 13, 13);">Ensure that your files are readily available across all your devices&nbsp;</span></p><a href="{% url 'drive:list' %}" class="btn btn-primary fs-5 me-2 py-2 px-4" type="button">Go To Drive</a><a href="{% url 'users:login' %}" class="btn btn-light fs-5 py-2 px-4" type="button" style="border-style: solid;border-color: var(--bs-btn-hover-border-color);">Sign In</a>
                <div style="padding: 8px 5px;font-size: 16px;" class="mt-0 pt-3"><span style="color: rgba(33,37,41,0.75);">Don't have an account?&nbsp;</span><a href="{% url 'users:signup' %}">Register</a></div>
            </div>
        </div>
    </section>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

drive/templates/main.html
{% extends 'partials/base.html' %}
{% block title %}Drive{% endblock %}
{% block content %}
<main style="font-size: 20px;">
    {% include './partials/error_alert.html' %}
    <nav class="navbar navbar-expand-md bg-body py-3">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="#"><span class="fs-3 fw-bold">Drive</span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-2"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-2">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"></li>
                    <li class="nav-item"></li>
                    <li class="nav-item"></li>
                    <li class="nav-item dropdown"><a class="nav-link" aria-expanded="false" data-bs-toggle="dropdown" href="#" style="background: rgb(13,110,253);color: rgb(255,255,255);border-radius: 5px;padding: 8px 16px;"><i class="fas fa-plus fs-6 me-2 align-self-end"></i>New</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" data-cy="new-folder-btn" data-bs-target="#modal-1" data-bs-toggle="modal" href="#">New Folder</a>
                            <label for="file-upload" class="dropdown-item" href="#" style="cursor:pointer;">Upload File</a>
                            <input type="file" class="dropdown-item" for="file-upload" id="file-upload" style="display:none;">
                    </li>
                </ul>
            </div>
            <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button class="btn ps-3 pb-0 pe-3 ms-0" style="font-size: 16px; color:blue; text-decoration:underline;">Logout</button>
            </form>
        </div>
    </nav>
    {% include 'partials/new_folder_modal.html' %}
    {% include 'partials/input_modal.html' with modal_id="modal-2" modal_title="Rename File" input_id="rename-file-input" on_ok="renameFile()" %}
    {% include 'partials/confirm_modal.html' with modal_id="modal-3" modal_title="Delete File" modal_content="Are you sure you want to delete file <span id='delete-file-name-display'> </span> ?" on_ok="deleteFile()" %}
    {% include 'partials/input_modal.html' with modal_id="modal-4" modal_title="Rename Folder" input_id="rename-folder-input" on_ok="renameFolder()" %}
    {% include 'partials/confirm_modal.html' with modal_id="modal-5" modal_title="Delete Folder" modal_content="<span id='folder-has-content-warning'> </span> Are you sure you want to delete the folder <span id='delete-folder-name-display'> </span>?" on_ok="deleteFolder()" %}

<span class="d-none" id="current-folder-id">
    {% if folder_id %}
        {{ folder_id }}
    {% endif %}
</span>
<template id="item-card-template">
    {% include './partials/file_item.html' with item="" rename_modal_id="#modal-2" delete_modal_id="#modal-3" %}
</template>
<div class="container-fliud"  style="padding: 0px 32px;">

    <div class="row gx-2 gy-2" id="file-items" style="padding: 8px 16px;">
        <div style="padding: 8px 16px;">
            {% if parent_folder_id %}
            <a href="/drive/folders/{{ parent_folder_id }}"> Back </a>
            {% else %}
            <a href="/drive/"> Back </a>
            {% endif %}
        </div>
        {% for item in folders %}
            {% include './partials/folder_item.html' with item=item rename_modal_id="#modal-4" delete_modal_id="#modal-5" %}
        {% endfor %}
        {% for item in files %}
            {% include './partials/file_item.html' with item=item rename_modal_id="#modal-2" delete_modal_id="#modal-3" %}
        {% endfor %}
    </div>
</div>
<div  class="position-fixed me-5" style="background: var(--bs-body-bg);right: 10px;bottom: 10px;padding: 8px 16px;text-align: left;">
    <a id="dropdown-btn" class="btn btn-primary mb-2" data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapse-1" href="#" role="button" style="width: 100%;">Upload Queue</a>
    <div class="collapse show" id="collapse-1" style="background: var(--bs-secondary-bg);">
        <ul class="list-group" id="upload-queue">
        </ul>
    </div>
</div>
</main>
{% endblock %}